name: Compile with SourceMod

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sm_version: ["1.10", "1.11"]

    steps:
      - uses: actions/checkout@v1

      - name: Set ENV variables
        run: |
          VERSION=$(git rev-list --count HEAD)
          SHORT=$(git describe --always --long --dirty)
          SOURCEMOD_PATH=$GITHUB_WORKSPACE/plugins
          echo ::set-env name=PLUGIN_VERSION::${{ matrix.SM_VERSION }}.$VERSION-$SHORT
          echo ::set-env name=SOURCEMOD_PATH::$SOURCEMOD_PATH
          echo ::set-env name=SCRIPTS_PATH::$SOURCEMOD_PATH/scripting/
          echo ::set-env name=PLUGINS_PATH::$SOURCEMOD_PATH/scripting/compiled/

      - name: Setup SourcePawn Compiler ${{matrix.SM_VERSION}}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION}}
      
      - name: Compile ModuleLIFT
        run: |
          for file in *.sp
          do
            echo -e "\nCompiling file..."
            spcomp -w234 -O2 -v2 -i $SCRIPTS_PATH/include $file
          done
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Move compiled plugins
        run: |
          mkdir -p Build/
          rsync -av --include='*/' --include="*.smx" --exclude="*" --remove-source-files $SCRIPTS_PATH/ Build/
      
      - name: Test Upload plugin files
        uses: actions/upload-artifact@master
        with: 
          name: Compiled plugins
          path: Build/
